### ISSUE TITLE
FYI: the line coding scheme is called 4b6b encoding

### ISSUE THREAD

**Issue by ecc1** [ps2/minimed_rf#10]
It's used to achieve DC balance, since each 6-bit symbol on the line has 3 ones and 3 zeroes.  Google turns up quite a few occurrences of it.

**Comment by ps2** [comment]
It's hard to google something you don't know the name of. :)  Took me a long time to decode it.  Was a fun puzzle, though.

**Comment by ps2** [comment]
Oh, I see, the readme still refers to it as unknown.  I'll update that.
